### ISSUE TITLE
README instruction is not clear

### ISSUE THREAD

**Issue by Externalnet** [KiefDelicious/ha-utils#3]
Hi,

The README instruction is not clear to me

"Replace Sensor Names: Ensure to replace the placeholder of 2 sensor names (everything_presence_lite_name) with the actual names of your sensors in Home Assistant."

The name of my sensor is "Everything Presence Lite 5c7da6"
So I have sensors like everything_presence_lite_5c7da6_target_1_active

I put the following in the code:
```

  __#change sensor name here
    fn_var1: $ex vars.sensor_name_prefix = "sensor.everything_presence_lite_5c7da6_";
    fn_var2: $ex vars.number_name_prefix = "number.everything_presence_lite_5c7da6_";
    fn_var3: $ex vars.is_inch_unit = false;__
```

But no go, I got lots of errors

Kr,

**Comment by Externalnet** [comment]
with everything_presence_lite_map_chart.yaml and replacing the two placeholders i get the following errors
I also removed zone 2 and zone 3 from the code (Still get errors)

![Image](https://github.com/user-attachments/assets/9a36f348-8478-46f2-8037-69cb90878cf1)

Code used:


```
type: custom:plotly-graph
refresh_interval: 1
hours_to_show: current_day
config:
  modeBarButtonsToRemove:
    - select2d
    - lasso2d
    - toImage
  displaylogo: false
layout:
  height: 240
  margin:
    l: 40
    r: 20
    t: 20
    b: 55
  showlegend: true
  xaxis:
    showticklabels: true
    dtick: 1000
    visible: true
    gridcolor: RGBA(200,200,200,0.15)
    zerolinecolor: RGBA(200,200,200,0.15)
    type: number
    fixedrange: true
    range:
      - -4000
      - 4000
  yaxis:
    showticklabels: true
    dtick: 1000
    visible: true
    gridcolor: RGBA(200,200,200,0.15)
    zerolinecolor: RGBA(200,200,200,0.15)
    scaleanchor: x
    scaleratio: 1
    fixedrange: true
    range:
      - 7500
      - 0
entities:
  - entity: ''
  #change sensor name here
    fn_var1: $ex vars.sensor_name_prefix = "sensor.everything_presence_lite_name_5c7da6_";
    fn_var2: $ex vars.number_name_prefix = "number.everything_presence_lite_name_5c7da6_";
    fn_var3: $ex vars.is_inch_unit = false;
  - entity: ''
    name: Target1
    marker:
      size: 10
      symbol: star-diamond
    line:
      shape: spline
      width: 5
    x:
      - >-
        $ex { var x = hass.states[vars.sensor_name_prefix + "target_1_x"].state;
        var y = hass.states[vars.sensor_name_prefix + "target_1_y"].state; if (x
        == 0 && y == 0) { return -9999 }; if (vars.is_inch_unit) { x = x * 25.4
        }; return x; }
    'y':
      - >-
        $ex { var x = hass.states[vars.sensor_name_prefix + "target_1_x"].state;
        var y = hass.states[vars.sensor_name_prefix + "target_1_y"].state; if (x
        == 0 && y == 0) { return -9999 }; if (vars.is_inch_unit) { y = y * 25.4
        }; return y; }
  - entity: ''
    name: Target2
    marker:
      size: 10
      symbol: star-diamond
    line:
      shape: spline
      width: 5
    x:
      - >-
        $ex { var x = hass.states[vars.sensor_name_prefix + "target_2_x"].state;
        var y = hass.states[vars.sensor_name_prefix + "target_2_y"].state; if (x
        == 0 && y == 0) { return -9999 }; if (vars.is_inch_unit) { x = x * 25.4
        }; return x; }
    'y':
      - >-
        $ex { var x = hass.states[vars.sensor_name_prefix + "target_2_x"].state;
        var y = hass.states[vars.sensor_name_prefix + "target_2_y"].state; if (x
        == 0 && y == 0) { return -9999 }; if (vars.is_inch_unit) { y = y * 25.4
        }; return y; }
  - entity: ''
    internal: false
    name: Target3
    marker:
      size: 10
      symbol: star-diamond
    line:
      shape: spline
      width: 5
    x:
      - >-
        $ex { var x = hass.states[vars.sensor_name_prefix + "target_3_x"].state;
        var y = hass.states[vars.sensor_name_prefix + "target_3_y"].state; if (x
        == 0 && y == 0) { return -9999 }; if (vars.is_inch_unit) { x = x * 25.4
        }; return x; }
    'y':
      - >-
        $ex { var x = hass.states[vars.sensor_name_prefix + "target_3_x"].state;
        var y = hass.states[vars.sensor_name_prefix + "target_3_y"].state; if (x
        == 0 && y == 0) { return -9999 }; if (vars.is_inch_unit) { y = y * 25.4
        }; return y; }
  - entity: ''
    name: Zone1
    mode: lines
    fill: toself
    fillcolor: RGBA(20,200,0,0.06)
    line:
      color: RGBA(20,200,0,0.2)
      shape: line
      width: 2
    x:
      - $ex hass.states[vars.number_name_prefix + "zone_1_begin_x"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_begin_x"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_end_x"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_end_x"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_begin_x"].state
    'y':
      - $ex hass.states[vars.number_name_prefix + "zone_1_begin_y"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_end_y"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_end_y"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_begin_y"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_begin_y"].state

  - entity: ''
    name: Coverage
    mode: lines
    fill: tonexty
    fillcolor: rgba(168, 216, 234, 0.15)
    hoverinfo: none
    line:
      shape: line
      width: 0.7
      dash: dot
    x:
      - 0
      - $ex 7500 * Math.sin((2 * Math.PI)/360 * 60)
      - 6500
      - 5500
      - 4500
      - 4000
      - 3000
      - 2000
      - 1000
      - 0
      - -1000
      - -2000
      - -3000
      - -4000
      - -4500
      - -5500
      - -6500
      - $ex -7500 * Math.sin((2 * Math.PI)/360 * 60)
      - 0
    'y':
      - 0
      - $ex 7500 * Math.cos((2 * Math.PI)/360 * 60)
      - $ex Math.sqrt( 7500**2 - 6500**2 )
      - $ex Math.sqrt( 7500**2 - 5500**2 )
      - $ex Math.sqrt( 7500**2 - 4500**2 )
      - $ex Math.sqrt( 7500**2 - 4000**2 )
      - $ex Math.sqrt( 7500**2 - 3000**2 )
      - $ex Math.sqrt( 7500**2 - 2000**2 )
      - $ex Math.sqrt( 7500**2 - 1000**2 )
      - 7500
      - $ex Math.sqrt( 7500**2 - 1000**2 )
      - $ex Math.sqrt( 7500**2 - 2000**2 )
      - $ex Math.sqrt( 7500**2 - 3000**2 )
      - $ex Math.sqrt( 7500**2 - 4000**2 )
      - $ex Math.sqrt( 7500**2 - 4500**2 )
      - $ex Math.sqrt( 7500**2 - 5500**2 )
      - $ex Math.sqrt( 7500**2 - 6500**2 )
      - $ex 7500 * Math.cos((2 * Math.PI)/360 * 60)
      - 0
raw_plotly_config: true
title: Live persons detected map
```

**Comment by Externalnet** [comment]
When using everything_presence_lite_map_chart-rotation-support.yaml i get

![Image](https://github.com/user-attachments/assets/d539a317-3e22-42cd-bdd2-69f5c417000b)

Both do not work as expected

**Comment by KiefDelicious** [comment]
Looks like still something wrong with the Entity ID's, or some sensors are not enabled. Can you put a screenshot of you device page in here? If the naming of the Entity ID's is changed, or they are not enabled (then it won't knows what entities to get the data from). Also to be sure, what are the Entity IDs of the Everything Presence Target 1 Active sensor and the Zone 1 Occupancy sensor?

I've tested it on firmware: 1.0.8, and the latest 1.2.2

(ps Lewis has released an Addon to configure zones, see https://everythingsmarthome.github.io/everything-presence-lite/Home%20Assistant/creating-zones.html. I'm using that now myself :)

**Comment by Externalnet** [comment]
Thanks for the link, I installed the zone configuration add-on. I guess the addon is only for configuring the zones/device. Does the add-on also provide a dashboard card ? 

Here some screenshots from my sensor names

![Image](https://github.com/user-attachments/assets/1c3bf7c0-79c3-41e5-8116-b3e452da287c)

![Image](https://github.com/user-attachments/assets/bcb2c737-e2c3-4d3b-a5ce-c9011777e794)


and the code used

```
type: custom:plotly-graph
refresh_interval: 1
hours_to_show: current_day
config:
  modeBarButtonsToRemove:
    - select2d
    - lasso2d
    - toImage
  displaylogo: false
layout:
  height: 240
  margin:
    l: 40
    r: 20
    t: 20
    b: 55
  showlegend: true
  xaxis:
    showticklabels: true
    dtick: 1000
    visible: true
    gridcolor: RGBA(200,200,200,0.15)
    zerolinecolor: RGBA(200,200,200,0.15)
    type: number
    fixedrange: true
    range:
      - -4000
      - 4000
  yaxis:
    showticklabels: true
    dtick: 1000
    visible: true
    gridcolor: RGBA(200,200,200,0.15)
    zerolinecolor: RGBA(200,200,200,0.15)
    scaleanchor: x
    scaleratio: 1
    fixedrange: true
    range:
      - 7500
      - 0
entities:
  - entity: ''
  #change sensor name here
    fn_var1: $ex vars.sensor_name_prefix = "sensor.everything_presence_lite_name_5c7da8_";
    fn_var2: $ex vars.number_name_prefix = "number.everything_presence_lite_name_5c7da8_";
    fn_var3: $ex vars.is_inch_unit = false;
  - entity: ''
    name: Target1
    marker:
      size: 10
      symbol: star-diamond
    line:
      shape: spline
      width: 5
    x:
      - >-
        $ex { var x = hass.states[vars.sensor_name_prefix + "target_1_x"].state;
        var y = hass.states[vars.sensor_name_prefix + "target_1_y"].state; if (x
        == 0 && y == 0) { return -9999 }; if (vars.is_inch_unit) { x = x * 25.4
        }; return x; }
    'y':
      - >-
        $ex { var x = hass.states[vars.sensor_name_prefix + "target_1_x"].state;
        var y = hass.states[vars.sensor_name_prefix + "target_1_y"].state; if (x
        == 0 && y == 0) { return -9999 }; if (vars.is_inch_unit) { y = y * 25.4
        }; return y; }
  - entity: ''
    name: Target2
    marker:
      size: 10
      symbol: star-diamond
    line:
      shape: spline
      width: 5
    x:
      - >-
        $ex { var x = hass.states[vars.sensor_name_prefix + "target_2_x"].state;
        var y = hass.states[vars.sensor_name_prefix + "target_2_y"].state; if (x
        == 0 && y == 0) { return -9999 }; if (vars.is_inch_unit) { x = x * 25.4
        }; return x; }
    'y':
      - >-
        $ex { var x = hass.states[vars.sensor_name_prefix + "target_2_x"].state;
        var y = hass.states[vars.sensor_name_prefix + "target_2_y"].state; if (x
        == 0 && y == 0) { return -9999 }; if (vars.is_inch_unit) { y = y * 25.4
        }; return y; }
  - entity: ''
    internal: false
    name: Target3
    marker:
      size: 10
      symbol: star-diamond
    line:
      shape: spline
      width: 5
    x:
      - >-
        $ex { var x = hass.states[vars.sensor_name_prefix + "target_3_x"].state;
        var y = hass.states[vars.sensor_name_prefix + "target_3_y"].state; if (x
        == 0 && y == 0) { return -9999 }; if (vars.is_inch_unit) { x = x * 25.4
        }; return x; }
    'y':
      - >-
        $ex { var x = hass.states[vars.sensor_name_prefix + "target_3_x"].state;
        var y = hass.states[vars.sensor_name_prefix + "target_3_y"].state; if (x
        == 0 && y == 0) { return -9999 }; if (vars.is_inch_unit) { y = y * 25.4
        }; return y; }
  - entity: ''
    name: Zone1
    mode: lines
    fill: toself
    fillcolor: RGBA(20,200,0,0.06)
    line:
      color: RGBA(20,200,0,0.2)
      shape: line
      width: 2
    x:
      - $ex hass.states[vars.number_name_prefix + "zone_1_begin_x"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_begin_x"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_end_x"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_end_x"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_begin_x"].state
    'y':
      - $ex hass.states[vars.number_name_prefix + "zone_1_begin_y"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_end_y"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_end_y"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_begin_y"].state
      - $ex hass.states[vars.number_name_prefix + "zone_1_begin_y"].state

  - entity: ''
    name: Coverage
    mode: lines
    fill: tonexty
    fillcolor: rgba(168, 216, 234, 0.15)
    hoverinfo: none
    line:
      shape: line
      width: 0.7
      dash: dot
    x:
      - 0
      - $ex 7500 * Math.sin((2 * Math.PI)/360 * 60)
      - 6500
      - 5500
      - 4500
      - 4000
      - 3000
      - 2000
      - 1000
      - 0
      - -1000
      - -2000
      - -3000
      - -4000
      - -4500
      - -5500
      - -6500
      - $ex -7500 * Math.sin((2 * Math.PI)/360 * 60)
      - 0
    'y':
      - 0
      - $ex 7500 * Math.cos((2 * Math.PI)/360 * 60)
      - $ex Math.sqrt( 7500**2 - 6500**2 )
      - $ex Math.sqrt( 7500**2 - 5500**2 )
      - $ex Math.sqrt( 7500**2 - 4500**2 )
      - $ex Math.sqrt( 7500**2 - 4000**2 )
      - $ex Math.sqrt( 7500**2 - 3000**2 )
      - $ex Math.sqrt( 7500**2 - 2000**2 )
      - $ex Math.sqrt( 7500**2 - 1000**2 )
      - 7500
      - $ex Math.sqrt( 7500**2 - 1000**2 )
      - $ex Math.sqrt( 7500**2 - 2000**2 )
      - $ex Math.sqrt( 7500**2 - 3000**2 )
      - $ex Math.sqrt( 7500**2 - 4000**2 )
      - $ex Math.sqrt( 7500**2 - 4500**2 )
      - $ex Math.sqrt( 7500**2 - 5500**2 )
      - $ex Math.sqrt( 7500**2 - 6500**2 )
      - $ex 7500 * Math.cos((2 * Math.PI)/360 * 60)
      - 0
raw_plotly_config: true
title: Live persons detected map

```
